package transientPojos;

public class DocTypes {
	public enum  DocType {BILL_MEDICAL, BILL_DENTAL, BILL_CAR, DOCUMENT_GOVERNMENT, DOCUMENT_STATEMENT, DOCUMENT_PRIVATE, ESTIMATE, PHOTO_PERSONAL, UNKNOWN }
}
